// Anti-Cheat and Automation Protection Shield - KASSINO-CKB
"use client";

import { useEffect, useState } from "react";

export default function AntiCheat() {
  const [isBotDetected, setIsBotDetected] = useState(false);

  useEffect(() => {
    if (typeof window === "undefined") return;

    // 1. Detect Automation (webdriver checks and chromedriver vars)
    const detectAutomation = () => {
      const isWebdriver = navigator.webdriver;
      
      const hasChromedriverVars = 
        // @ts-ignore
        window.cdc_adoQpoasnfa76pfcZLmcfl_Array || 
        // @ts-ignore
        window.cdc_adoQpoasnfa76pfcZLmcfl_Symbol ||
        // @ts-ignore
        document.$cdc_asdjflasutopfhvcZlmcfl_;

      if (isWebdriver || hasChromedriverVars) {
        setIsBotDetected(true);
        console.warn("Automation/Agent detected!");
      }
    };
    
    detectAutomation();

    // 2. Block Keyboard Shortcuts & Right-Clicks
    const handleContextMenu = (e: MouseEvent) => {
      e.preventDefault();
    };

    const handleKeyDown = (e: KeyboardEvent) => {
      // F12 key
      if (e.key === "F12") {
        e.preventDefault();
        triggerDebugger();
      }
      
      // Ctrl+Shift+I / Cmd+Opt+I (Inspect)
      if ((e.ctrlKey || e.metaKey) && e.shiftKey && e.key === "I") {
        e.preventDefault();
        triggerDebugger();
      }
      
      // Ctrl+Shift+J / Cmd+Opt+J (Console)
      if ((e.ctrlKey || e.metaKey) && e.shiftKey && e.key === "J") {
        e.preventDefault();
        triggerDebugger();
      }
      
      // Ctrl+Shift+C (Element Selector)
      if ((e.ctrlKey || e.metaKey) && e.shiftKey && e.key === "C") {
        e.preventDefault();
        triggerDebugger();
      }
      
      // Ctrl+U (View Source)
      if ((e.ctrlKey || e.metaKey) && e.key === "U") {
        e.preventDefault();
      }
    };

    window.addEventListener("contextmenu", handleContextMenu);
    window.addEventListener("keydown", handleKeyDown);

    // 3. Infinite Debugger Loop to freeze page if DevTools is opened
    // When DevTools is closed, the debugger has no effect. 
    // When opened, the browser hits the breakpoint loop, pausing the bot/hacker.
    // Secure: We bypass this on mobile devices to prevent performance degradation/freezing on cellular browsers.
    const isMobileDevice = /Mobi|Android|iPhone|iPad|iPod|Windows Phone/i.test(navigator.userAgent);

    const triggerDebugger = () => {
      (function() {
        debugger;
      })();
    };

    let debuggerInterval: NodeJS.Timeout | null = null;
    if (!isMobileDevice) {
      debuggerInterval = setInterval(() => {
        triggerDebugger();
      }, 150);
    }

    // 4. Overwrite console logging in production to prevent bots from scraping outputs
    const consoleTrap = () => {
      try {
        const dummy = () => {};
        if (process.env.NODE_ENV === "production") {
          window.console.log = dummy;
          window.console.info = dummy;
          window.console.warn = dummy;
          window.console.debug = dummy;
        }
      } catch (e) {}
    };
    consoleTrap();

    // 5. Block Untrusted Mouse clicks (AI agents and auto clickers)
    // isTrusted is true ONLY when generated by actual user device hardware mouse/touch.
    // If generated by scripts (.click()), it is false. We intercept at capturing phase (true).
    const handleDocumentClick = (e: MouseEvent) => {
      if (e.isTrusted === false) {
        e.preventDefault();
        e.stopPropagation();
        setIsBotDetected(true);
        console.warn("Script-generated click blocked!");
      }
    };
    
    document.addEventListener("click", handleDocumentClick, true);

    return () => {
      window.removeEventListener("contextmenu", handleContextMenu);
      window.removeEventListener("keydown", handleKeyDown);
      if (debuggerInterval) clearInterval(debuggerInterval);
      document.removeEventListener("click", handleDocumentClick, true);
    };
  }, []);

  if (isBotDetected) {
    return (
      <div style={{
        position: "fixed",
        inset: 0,
        background: "#0c0202",
        color: "#ffcdd2",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 9999999,
        fontFamily: "sans-serif",
        textAlign: "center",
        padding: "32px",
        boxSizing: "border-box"
      }}>
        <div style={{
          padding: "40px",
          borderRadius: "16px",
          background: "rgba(20, 5, 5, 0.8)",
          border: "1px solid rgba(211, 47, 47, 0.3)",
          boxShadow: "0 10px 40px rgba(0,0,0,0.8)",
          maxWidth: "600px"
        }}>
          <h1 style={{ fontSize: "2rem", color: "#ef5350", marginBottom: "16px", letterSpacing: "1px" }}>
            🛡️ DETECTOR DE AUTOMAÇÃO ATIVO
          </h1>
          <p style={{ fontSize: "1.1rem", color: "#e0e0e0", lineHeight: "1.6", margin: "0 0 24px 0" }}>
            Detectamos ferramentas de automação (bots, extensões de simulação de clique ou agentes de IA) ativas no seu navegador.
          </p>
          <p style={{ fontSize: "0.95rem", color: "var(--text-muted)", lineHeight: "1.5", margin: 0 }}>
            Para garantir uma competição honesta e justa entre os jogadores na nossa arena, o uso de automação é proibido. Por favor, feche as ferramentas de desenvolvedor e recarregue a página.
          </p>
        </div>
      </div>
    );
  }

  return null;
}
